language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
        - COMPILER_CXX=g++-5
        - COMPILER_C=gcc-5
      install:
        - export CXX=${COMPILER_CXX}
        - export CC=${COMPILER_C}
        - pip install conan
        - conan install --build=missing -s compiler=gcc -s compiler.version=5.4 -s compiler.libcxx=libstdc++

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-3.8
          packages:
            - clang-3.8
            - libc++-dev
      env:
        - COMPILER_CXX=clang++-3.8
        - COMPILER_C=clang-3.8
        - CMAKE_EXTRA_FLAGS=-DCMAKE_CXX_FLAGS=-stdlib=libc++
      install:
        - export CXX=${COMPILER_CXX}
        - export CC=${COMPILER_C}
        - pip install conan
        - conan install --build=missing -s compiler=clang -s compiler.version=3.8 -s compiler.libcxx=libc++

script:
  - export CXX=${COMPILER_CXX}
  - export CC=${COMPILER_C}
  - mkdir build && cd build
  - cmake ${CMAKE_EXTRA_FLAGS} .. && make
  - make test || ( cat Testing/Temporary/LastTest.log && false )

