language: cpp

sudo: required
services:
  - docker

before_install:
  - docker pull sirvestnik/cxx-conan-gcc-6

script:
  - docker run -v ${PWD}:/home/builder/src -w /home/builder/src --user builder sirvestnik/cxx-conan-gcc-6 /bin/sh .travis/autobuild.sh gcc-6 g++-6 libstdc++11 Release
