language: cpp

sudo: required
services:
  - docker

before_install:
  - docker pull sirvestnik/cxx-conan-gcc-5

script:
  - docker run -v ${PWD}:/home/builder/src sirvestnik/cxx-conan-gcc-5 libstdc++11 Release
