version: 1.0.{build}

environment:
  global:
    CTEST_OUTPUT_ON_FAILURE: True
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_CMAKE_GENERATOR: Visual Studio 14 2015 Win64
      CONAN_VC_VER: 14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      CONAN_VC_VER: 15

install:
- cmd: >-
    pip.exe install conan

    mkdir build

    cd build

    conan remote add VestniK https://api.bintray.com/conan/pdeps/deps

    conan install -o gtest:shared=False -s arch=x86_64 -s compiler="Visual Studio" -s compiler.version=%CONAN_VC_VER% -s compiler.runtime=MT -s build_type=Release --build=missing ..

build_script:
- cmd: >-
    cmake -G "%CONAN_CMAKE_GENERATOR%" -DCONAN=On -DBUILD_SHARED_LIBS=Off ..

    cmake --build . --config ReleaseStatic

test_script:
  - cmake --build . --config ReleaseStatic --target RUN_TESTS
