version: 1.0.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_CMAKE_GENERATOR: Visual Studio 15 2017 Win64

install:
- cmd: >-
    pip.exe install conan

    cmd.exe /c conan install

    conan --version

    conan profile update settings.compiler.runtime=MT default

    conan profile show default

    mkdir build

    cd build

    conan install --build=missing ..

build_script:
- cmd: >-
    cmake -G "%CONAN_CMAKE_GENERATOR%" -DCONAN=On ..

    cmake --build . --config ReleaseStatic

test_script:
  - cmd: .\bin\unit_tests.exe
