version: 1.0.{build}

install:
- cmd: >-
    pip.exe install conan

    mkdir build

    cd build

    conan install --build=missing ..

build_script:
- cmd: >-
    cmake -G "Visual Studio 14 2015 Win64" ..

    cmake --build . --config Release

test_script:
  - cmd: .\bin\unit_tests.exe
